name: "Hello Actions"
description: "Greet pengfei"
author: "pengfei.liu@hotmail.fr"
inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "mic"
  color: "purple"
